# Generated by Django 2.2.2 on 2019-06-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
