# Generated by Django 2.2.3 on 2019-08-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190620_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mag',
            options={'verbose_name': 'Магазин'},
        ),
    ]
