# Generated by Django 2.2.3 on 2019-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190806_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('message', models.TextField(verbose_name='Сообщение')),
                
            ],
            options={
                'verbose_name': 'Отзывы',
            },
        ),
        migrations.AlterField(
            model_name='mag',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
