# Generated by Django 2.2.3 on 2019-08-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190813_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mag',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №1'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №2'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №3'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №4'),
        ),
        migrations.AlterField(
            model_name='mag',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Изображение №5'),
        ),
    ]
